### ISSUE TITLE
EIP196 bounds checking too strict

### ISSUE THREAD

**Issue by shemnon** [matter-labs/eip1962#15]
The code in this library expects that all calls will have exact inputs and outputs (as does EIP2537).  However the EIP for add and multiply allows for sloppiness in the call length - 

> For both precompiled contracts, if the input is shorter than expected, it is assumed to be virtually padded with zeros at the end (i.e. compatible with the semantics of the CALLDATALOAD opcode). If the input is longer than expected, surplus bytes at the end are ignored. \[[EIP-196](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-196.md#encoding)\]

The pairing check is strict, and appears to be working correctly as currently coded.

> If the input length is not a multiple of 192, the call fails. Empty input is valid and results in returning one. \[[EIP-197](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-197.md#specification)\]

Reference tests verify at least the add and mul encoding rules.

**Comment by shemnon** [comment]
This fix would be very useful for Besu

before
BNADD
BNADD for 165 gas.
BNMUL
BNMUL for 19109 gas.

after
BNADD
BNADD for 131 gas.
BNMUL
BNMUL for 5166 gas.

**Comment by shamatar** [comment]
Nethermind has implemented padding/trimming before the call of this functions for exactly the same reason, but I will remove them to follow the spec literally.

**Comment by shemnon** [comment]
We have a workaround doing the same as well, but if it's advertising EIP196 in the function name it should conform IMHO.

**Comment by shamatar** [comment]
Updated in the "tuning" branch, will merge into master after a little more testing.

**Comment by shemnon** [comment]
https://github.com/matter-labs/eip1962/commit/977253fe819bcb154b19d74ee5e68beac83054a4 fixed the issue
