### ISSUE TITLE
EIP197 consensus failure

### ISSUE THREAD

**Issue by shemnon** [matter-labs/eip1962#17]
https://goerli.etherscan.io/block/1238955

call to BN Pairing with args

`0x0fc6ebd1758207e311a99674dc77d28128643c057fb9ca2c92b4205b6bf57ed21e50042f97b7a1f2768fa15f6683eca9ee7fa8ee655d94246ab85fb1da3f0b90198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa2b101be01b2f064cba109e065dc0b5e5bf6b64ed4054b82af3a7e6e34c1e20051a4d9ceecf9115a98efd147c4abb2684102d3e925938989153b9ff330523cdb408d554bf59102bbb961ba81107ec71785ef9ce6638e5332b6c1a58b87447d18101cf7cc93bfbf7b2c5f04a3bc9cb8b72bbcf2defcabdceb09860c493bdf1588d02cb2a424885c9e412b94c40905b359e3043275cd29f5b557f008cd0a3e0c0dc204e5d81d86c561f9344ad5f122a625f259996b065b80cbbe74a9ad97b6d7cc2`

_Should_ return `0x0000000000000000000000000000000000000000000000000000000000000001`, matter labs returns `0x0000000000000000000000000000000000000000000000000000000000000000`.

**Comment by shemnon** [comment]
To be clear `eip196_perform_operation` called with `EIP196_PAIR_OPERATION_RAW_VALUE` as the op

**Comment by shemnon** [comment]
trace https://gist.github.com/shemnon/43690316babfe176c51a0b7a50416d58
Differences start at line 2126

**Comment by shamatar** [comment]
Will review it in a local morning, thank you!

**Comment by shamatar** [comment]
@shemnon Can you also tell me the branch/commit being used by the node?

**Comment by shemnon** [comment]
I didn't commit the besu code because it failed to sync goerli.  The code version of matter-labs is https://github.com/matter-labs/eip1962/commit/fb1c7028417db090ba5312c22837e853c6159b4a

The besu code that found this (and others) is mostly https://github.com/shemnon/besu/tree/matterLabsAltBN but you will need to clone https://github.com/hyperledger/besu-native and then run run `./gradlew publishToMavenLocal`. a goerli full sync will find it within an hour.

3617444 is also another block that trips it.  There are many more.

**Comment by shemnon** [comment]
Basically I was validating that it worked before pushing a PR.  Performance is _much_ better than the old sputnikvm code we were using.

**Comment by shamatar** [comment]
@shemnon Can you try the latest master commit https://github.com/matter-labs/eip1962/commit/f8cba27d00f1d181ad18a2fb8ed3616b6d32759c

**Comment by shemnon** [comment]
Single block check works.  Let me do a full goerli import.

**Comment by shemnon** [comment]
Goreli full synced worked.  25% overall improvement (up tp 4x locally in the precompile).  There's a lot of BLS calls late in the chain.
